return {
  name = "Hiker",
  id = "c_mod_hiker_1",
  rules = {
    custom = {
      { id = "debuff_played_cards" },
      { id = "no_shop_planets" },
      {
        id = "cm_credit",
        value = "sharktamer & Djynasty",
      },
    },
  },
  jokers = {
    { id = "j_hiker", eternal = true },
  },
  deck = {
    type = "Plasma Deck",
    cards = {
      { s = "D", r = "A", g = "Purple" },
      { s = "D", r = "2", g = "Purple" },
      { s = "D", r = "3", g = "Purple" },
      { s = "D", r = "4", g = "Purple" },
      { s = "D", r = "5", g = "Purple" },
      { s = "D", r = "6", g = "Purple" },
      { s = "D", r = "7", g = "Purple" },
      { s = "D", r = "8", g = "Purple" },
      { s = "D", r = "9", g = "Purple" },
      { s = "D", r = "T", g = "Purple" },
      { s = "D", r = "J", g = "Purple" },
      { s = "D", r = "Q", g = "Purple" },
      { s = "D", r = "K", g = "Purple" },
      { s = "C", r = "A", g = "Purple" },
      { s = "C", r = "2", g = "Purple" },
      { s = "C", r = "3", g = "Purple" },
      { s = "C", r = "4", g = "Purple" },
      { s = "C", r = "5", g = "Purple" },
      { s = "C", r = "6", g = "Purple" },
      { s = "C", r = "7", g = "Purple" },
      { s = "C", r = "8", g = "Purple" },
      { s = "C", r = "9", g = "Purple" },
      { s = "C", r = "T", g = "Purple" },
      { s = "C", r = "J", g = "Purple" },
      { s = "C", r = "Q", g = "Purple" },
      { s = "C", r = "K", g = "Purple" },
      { s = "H", r = "A", g = "Purple" },
      { s = "H", r = "2", g = "Purple" },
      { s = "H", r = "3", g = "Purple" },
      { s = "H", r = "4", g = "Purple" },
      { s = "H", r = "5", g = "Purple" },
      { s = "H", r = "6", g = "Purple" },
      { s = "H", r = "7", g = "Purple" },
      { s = "H", r = "8", g = "Purple" },
      { s = "H", r = "9", g = "Purple" },
      { s = "H", r = "T", g = "Purple" },
      { s = "H", r = "J", g = "Purple" },
      { s = "H", r = "Q", g = "Purple" },
      { s = "H", r = "K", g = "Purple" },
      { s = "S", r = "A", g = "Purple" },
      { s = "S", r = "2", g = "Purple" },
      { s = "S", r = "3", g = "Purple" },
      { s = "S", r = "4", g = "Purple" },
      { s = "S", r = "5", g = "Purple" },
      { s = "S", r = "6", g = "Purple" },
      { s = "S", r = "7", g = "Purple" },
      { s = "S", r = "8", g = "Purple" },
      { s = "S", r = "9", g = "Purple" },
      { s = "S", r = "T", g = "Purple" },
      { s = "S", r = "J", g = "Purple" },
      { s = "S", r = "Q", g = "Purple" },
      { s = "S", r = "K", g = "Purple" },
    },
  },
  restrictions = {
    banned_cards = {
      -- chip jokers
      { id = "j_arrowhead" },
      { id = "j_banner" },
      { id = "j_blue_joker" },
      { id = "j_bull" },
      { id = "j_castle" },
      { id = "j_clever" },
      { id = "j_crafty" },
      { id = "j_devious" },
      { id = "j_ice_cream" },
      { id = "j_odd_todd" },
      { id = "j_runner" },
      { id = "j_scary_face" },
      { id = "j_sly" },
      { id = "j_square" },
      { id = "j_stone" },
      { id = "j_stuntman" },
      { id = "j_wee" },
      { id = "j_wily" },
      { id = "j_scholar" },
      { id = "j_walkie_talkie" },
      -- retrigger xmult
      { id = "j_ancient" },
      { id = "j_baron" },
      { id = "j_bloodstone" },
      { id = "j_photograph" },
      { id = "j_idol" },
      { id = "j_triboulet" },
      -- other jokers
      { id = "j_marble" },
      -- consumables
      { id = "c_heirophant" },
      { id = "c_high_priestess" },
      { id = "c_wheel_of_fortune" },
      { id = "c_tower" },
      { id = "c_aura" },
      { id = "c_grim" },
      { id = "c_familiar" },
      { id = "c_incantation" },
      -- packs
      {
        id = "p_standard_normal_1",
        ids = {
          "p_standard_normal_1",
          "p_standard_normal_2",
          "p_standard_normal_3",
          "p_standard_normal_4",
          "p_standard_jumbo_1",
          "p_standard_jumbo_2",
          "p_standard_mega_1",
          "p_standard_mega_2",
        },
      },
      {
        id = "p_celestial_normal_1",
        ids = {
          "p_celestial_normal_1",
          "p_celestial_normal_2",
          "p_celestial_normal_3",
          "p_celestial_normal_4",
          "p_celestial_jumbo_1",
          "p_celestial_jumbo_2",
          "p_celestial_mega_1",
          "p_celestial_mega_2",
        },
      },
      -- vouchers
      { id = "v_magic_trick" },
      { id = "v_illusion" },
    },
    banned_tags = {
      { id = "tag_standard" },
      { id = "tag_meteor" },
      { id = "tag_foil" },
    },
    banned_other = {
      { id = "bl_arm", type = "blind" },
      { id = "bl_eye", type = "blind" },
      { id = "bl_mouth", type = "blind" },
      { id = "bl_ox", type = "blind" },
    },
  },
}
