local joker_names = {
    "j_joker",
    "j_jolly",
    "j_zany",
    "j_mad",
    "j_crazy",
    "j_droll",
    "j_sly",
    "j_wily",
    "j_clever",
    "j_devious",
    "j_crafty",
    "j_half",
    "j_fortune_teller",
    "j_juggler",
    "j_drunkard",
    "j_stone",
    "j_golden",
    "j_stencil",
    "j_four_fingers",
    "j_mime",
    "j_credit_card",
    "j_greedy_joker",
    "j_lusty_joker",
    "j_wrathful_joker",
    "j_gluttenous_joker",
    "j_ceremonial",
    "j_banner",
    "j_mystic_summit",
    "j_marble",
    "j_loyalty_card",
    "j_8_ball",
    "j_dusk",
    "j_chaos",
    "j_misprint",
    "j_raised_fist",
    "j_fibonacci",
    "j_steel_joker",
    "j_scary_face",
    "j_abstract",
    "j_delayed_grat",
    "j_pareidolia",
    "j_hack",
    -- "j_gros_michel",
    "j_even_steven",
    "j_odd_todd",
    "j_scholar",
    "j_business",
    "j_supernova",
    "j_superposition",
    "j_ride_the_bus",
    "j_space",
    -- "j_egg",
    "j_burglar",
    "j_blackboard",
    "j_runner",
    -- "j_ice_cream",
    "j_dna",
    "j_splash",
    "j_blue_joker",
    "j_sixth_sense",
    "j_constellation",
    "j_hiker",
    "j_faceless",
    "j_todo_list",
    "j_ticket",
    "j_mr_bones",
    "j_acrobat",
    "j_sock_and_buskin",
    "j_green_joker",
    "j_swashbuckler",
    "j_troubadour",
    "j_certificate",
    "j_smeared",
    "j_throwback",
    "j_hanging_chad",
    "j_rough_gem",
    "j_bloodstone",
    "j_arrowhead",
    "j_onyx_agate",
    "j_glass",
    "j_ring_master",
    "j_flower_pot",
    "j_blueprint",
    "j_wee",
    "j_merry_andy",
    "j_oops",
    "j_idol",
    "j_seeing_double",
    "j_matador",
    "j_hit_the_road",
    "j_duo",
    "j_trio",
    "j_family",
    "j_order",
    "j_tribe",
    -- "j_cavendish",
    "j_card_sharp",
    "j_red_card",
    "j_madness",
    "j_square",
    "j_seance",
    "j_riff_raff",
    "j_vampire",
    "j_shortcut",
    "j_hologram",
    "j_vagabond",
    "j_baron",
    "j_cloud_9",
    "j_rocket",
    "j_obelisk",
    "j_midas_mask",
    "j_luchador",
    "j_photograph",
    "j_gift",
    -- "j_turtle_bean",
    "j_erosion",
    "j_reserved_parking",
    "j_mail",
    "j_to_the_moon",
    "j_hallucination",
    "j_lucky_cat",
    "j_baseball",
    "j_bull",
    -- "j_diet_cola",
    "j_trading",
    "j_flash",
    -- "j_popcorn",
    -- "j_ramen",
    "j_trousers",
    "j_ancient",
    "j_walkie_talkie",
    -- "j_selzer",
    "j_castle",
    "j_smiley",
    "j_campfire",
    "j_stuntman",
    "j_invisible",
    "j_brainstorm",
    "j_satellite",
    "j_shoot_the_moon",
    "j_drivers_license",
    "j_cartomancer",
    "j_astronomer",
    "j_burnt",
    "j_bootstraps",
    "j_caino",
    "j_triboulet",
    "j_yorick",
    --"j_chicot",
    "j_perkeo",
}

local banned_jokers = {}
for _, v in ipairs(joker_names) do
    table.insert(banned_jokers, { id = v })
end

return {
  name = "Freeze Dried (Food Jokers)",
  id = "c_mod_freeze_dried_food_1",
  rules = {
    custom = {
	  {
        id = "cm_no_after_hand",
        value = true,
      },
	  {
        id = "cm_no_after_round",
        value = true,
      },
	  {
        id = "cm_no_on_discard",
        value = true,
      },
      {
        id = "cm_credit",
        value = "Millie",
      },
    },
    modifiers = {
    },
  },
  jokers = {
    { id = "j_ring_master", eternal = true, edition = "negative" },
  },
  consumeables = {},
  vouchers = {},
  deck = {
    type = "Challenge Deck",
  },
  restrictions = {
    banned_cards = banned_jokers,
    banned_tags = {},
    banned_other = {},
  },
}
