return {
  name = "Oops, All Sixes!",
  id = "c_mod_sixes_1",
  rules = {
    custom = {
      { id = "cm_noshop"},
      { id = "no_reward_specific", value = "Small"},
      {
        id = "cm_credit",
        value = "Cheerio1101",
      },
    },
    modifiers = {
      { id = "discards", value = 2 },
    },
  },
  jokers = {
    { id = "j_oops", eternal = true, edition = "negative" },
    { id = "j_sixth_sense", eternal = true, edition = "negative" },
  },
  consumeables = {},
  vouchers = {},
  deck = {
    --17 hearts/spades, 16 diamonds/clubs
    cards = {
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
    },
    type = "Challenge Deck",
  },
  restrictions = {
    banned_cards = {
      --maybe ban celestial packs, but too many buffoon packs trivializes the challenge so maybe not.
      {
        id = "p_arcana_normal_1",
        ids = {
          "p_arcana_normal_1",
          "p_arcana_normal_2",
          "p_arcana_normal_3",
          "p_arcana_normal_4",
          "p_arcana_jumbo_1",
          "p_arcana_jumbo_2",
          "p_arcana_mega_1",
          "p_arcana_mega_2",
        },
      },
      {
        id = "p_buffoon_normal_1",
        ids = { "p_buffoon_normal_1", "p_buffoon_normal_2", "p_buffoon_jumbo_1", "p_buffoon_mega_1" },
      },
      {
        id = "p_spectral_normal_1",
        ids = { "p_spectral_normal_1", "p_spectral_normal_2", "p_spectral_jumbo_1", "p_spectral_mega_1" },
      },
    },
    banned_tags = {},
    banned_other = {},
  },
}
